version: '3.4'

x-common-variables: &common-variables
  MYSQL_DATABASE: wequeue
  MYSQL_USER: wequeue
  MYSQL_PASSWORD: wequeue

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4575:4575'       
      - '4576:4576'  
      - '4568:4568'  
      - '4574:4574'  
      - '4569:4569'  
    environment:
      SERVICES: lambda,sns,kinesis,sqs,dynamodb       
      LAMBDA_EXECUTOR: local
      DOCKER_HOST: unix:///var/run/docker.sock
      DEBUG: 1
    volumes:
      - "/private${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      <<: *common-variables
  
  wequeue:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    links:
      - mysql:mysql
      - localstack:localstack    
    ports:
      - '8080:8080'
    environment:
      ENGINES_AWS_LAMBDA_EXECUTIONROLE: arn:role:dummy  
      GO_ENVIRONMENT: local
      NEW_RELIC_LICENSE_KEY: 1bd07dd02fbaade38e40f19961382100bd9259aa
      NEW_RELIC_APP_NAME: bondi
      <<: *common-variables

  consumer:
    build:
      context: consumer
      dockerfile: Dockerfile    
    ports:
      - '9000:9000'  
