version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4575:4575'       
  mysql:
    image: mysql:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile.mysql      
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: wequeue
      MYSQL_ROOT_PASSWORD: root 

  wequeue:
          #image: signature-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - 'mysql'
    links:
      - mysql:mysql
      - localstack:localstack    
    ports:
      - '8080:8080'
 
