version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4575:4575'       
      - '4562:4562'  
    environment:
      SERVICES: lambda,sns,kinesis,sqs       
      LAMBDA_EXECUTOR: local
      DOCKER_HOST: unix:///var/run/docker.sock
      DEBUG: 1
    volumes:
      - "/private${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mysql:
    image: mysql:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile.mysql      
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: wequeue
      MYSQL_ROOT_PASSWORD: root 

  wequeue:
          #image: signature-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - 'mysql'
    links:
      - mysql:mysql
      - localstack:localstack    
    ports:
      - '8080:8080'
 
