engines:
  AWS:
    region: us-east-1
    lambda:
      executionRole: 
      zipDir: /go/src/github.com/wenance/wequeue-management_api/lambda/

database:
  mysql:
    user: root
    password: root
    database: wequeue
    host: mysql