engines:
  AWS:
    region: us-east-1
    lambda:
      executionRole: arn:aws:iam::719849485599:role/AmazonECSTask-wequeue-service-dev
      zipDir: /go/src/github.com/wenance/wequeue-management_api/lambda/

database:
  mysql:
    user: root
    password: root
    database: wequeue
    host: mysql